sonar.projectKey=typescript-jumpstart
sonar.projectName=typescript-jumpstart
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Language
sonar.language=ts

# TypeScript config
sonar.typescript.tsconfigPath=tsconfig.json

# Source files location
sonar.sources=.

# Ignore files
sonar.exclusions=**/node_modules/**, **/dist/**
