import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';
import jwksClient from 'jwks-rsa';
import { log } from '../utils/logger';
import HttpException from '../utils/errors.utills';

/**
 * GitHub Actions OIDC JWT claims interface
 */
interface IGitHubOIDCClaims {
	iss: string; // Issuer: https://token.actions.githubusercontent.com
	sub: string; // Subject: repo:owner/repo:ref:refs/heads/main
	aud: string; // Audience: your API URL
	ref: string; // Git ref (e.g., refs/heads/main)
	sha: string; // Commit SHA
	repository: string; // Repository name (owner/repo)
	repository_owner: string; // Repository owner
	repository_owner_id: string; // Repository owner ID
	run_id: string; // Workflow run ID
	run_number: string; // Workflow run number
	run_attempt: string; // Workflow run attempt
	actor: string; // GitHub user who triggered the workflow
	workflow: string; // Workflow name
	event_name: string; // Event that triggered the workflow
	job_workflow_ref: string; // Workflow reference
	environment?: string; // Optional: GitHub environment name
	iat: number; // Issued at (timestamp)
	exp: number; // Expires at (timestamp)
	[key: string]: unknown; // Allow additional claims
}

/**
 * Extended Request interface with GitHub OIDC claims
 */
export interface IRequestWithGitHub extends Request {
	github?: IGitHubOIDCClaims;
}

/**
 * JWKS client for fetching GitHub's public keys
 */
const client = jwksClient({
	jwksUri: 'https://token.actions.githubusercontent.com/.well-known/jwks',
	cache: true,
	cacheMaxAge: 600000, // Cache keys for 10 minutes
	rateLimit: true,
	jwksRequestsPerMinute: 10,
});

/**
 * Get the signing key from JWKS
 */
function getKey(header: jwt.JwtHeader, callback: jwt.SigningKeyCallback): void {
	client.getSigningKey(header.kid, (err, key) => {
		if (err) {
			callback(err);
			return;
		}
		const signingKey = key?.getPublicKey();
		callback(null, signingKey);
	});
}

/**
 * Verify and decode GitHub OIDC JWT token
 */
function verifyGitHubToken(token: string): Promise<IGitHubOIDCClaims> {
	return new Promise((resolve, reject) => {
		jwt.verify(
			token,
			getKey,
			{
				algorithms: ['RS256'],
				issuer: 'https://token.actions.githubusercontent.com',
				// Audience verification is important - set your API URL in env
				audience: process.env.GITHUB_OIDC_AUDIENCE || '',
			},
			(err, decoded) => {
				if (err) {
					reject(err);
					return;
				}
				resolve(decoded as IGitHubOIDCClaims);
			},
		);
	});
}

/**
 * Middleware to authenticate GitHub Actions OIDC tokens
 *
 * This validates JWT tokens generated by GitHub Actions OIDC provider.
 * The token is automatically generated at runtime (no secrets stored in GitHub).
 *
 * Usage in routes:
 * router.post('/deploy/start', authenticateGitHub, DeployController.startDeployment);
 */
export async function authenticateGitHub(
	req: IRequestWithGitHub,
	res: Response,
	next: NextFunction,
): Promise<void> {
	try {
		// Extract Authorization header
		const authHeader = req.headers.authorization;

		if (!authHeader) {
			throw new HttpException(
				401,
				'Missing Authorization header',
				'AUTH_MISSING',
				'Authorization header is required',
			);
		}

		// Check Bearer token format
		if (!authHeader.startsWith('Bearer ')) {
			throw new HttpException(
				401,
				'Invalid Authorization header format. Expected: Bearer <token>',
				'AUTH_INVALID_FORMAT',
				'Authorization header must use Bearer token',
			);
		}

		// Extract token
		const token = authHeader.substring(7).trim();

		if (!token) {
			throw new HttpException(
				401,
				'Empty token provided',
				'AUTH_EMPTY_TOKEN',
				'Token cannot be empty',
			);
		}

		// Verify JWT token
		const claims = await verifyGitHubToken(token);

		// Validate repository if whitelist is configured
		const allowedRepos = process.env.ALLOWED_GITHUB_REPOS?.split(',').map((r) =>
			r.trim(),
		);

		if (allowedRepos && allowedRepos.length > 0) {
			if (!allowedRepos.includes(claims.repository)) {
				log.warn('Unauthorized repository attempted access', {
					repository: claims.repository,
					actor: claims.actor,
					workflow: claims.workflow,
				});

				throw new HttpException(
					403,
					`Repository '${claims.repository}' is not authorized to access this API`,
					'AUTH_REPO_FORBIDDEN',
					'Repository not in whitelist',
				);
			}
		}

		// Validate environment if specified (optional)
		const allowedEnvironments = process.env.ALLOWED_GITHUB_ENVIRONMENTS?.split(
			',',
		).map((e) => e.trim());

		if (
			allowedEnvironments &&
			allowedEnvironments.length > 0 &&
			claims.environment &&
			typeof claims.environment === 'string'
		) {
			if (!allowedEnvironments.includes(claims.environment)) {
				log.warn('Unauthorized environment attempted access', {
					environment: claims.environment,
					repository: claims.repository,
				});

				throw new HttpException(
					403,
					`Environment '${claims.environment}' is not authorized`,
					'AUTH_ENV_FORBIDDEN',
					'Environment not in whitelist',
				);
			}
		}

		// Attach GitHub claims to request object for use in controllers
		req.github = claims;

		log.info('GitHub OIDC authentication successful', {
			repository: claims.repository,
			actor: claims.actor,
			workflow: claims.workflow,
			ref: claims.ref,
			runId: claims.run_id,
		});

		next();
	} catch (error) {
		if (error instanceof HttpException) {
			next(error);
			return;
		}

		// Handle JWT verification errors
		if (error instanceof jwt.JsonWebTokenError) {
			log.error('JWT verification failed', {
				error: error.message,
				name: error.name,
			});

			next(
				new HttpException(
					401,
					`Invalid token: ${error.message}`,
					'AUTH_JWT_INVALID',
					'JWT verification failed',
				),
			);
			return;
		}

		if (error instanceof jwt.TokenExpiredError) {
			log.error('JWT token expired', {
				expiredAt: error.expiredAt,
			});

			next(
				new HttpException(
					401,
					'Token has expired',
					'AUTH_JWT_EXPIRED',
					'JWT token expired',
				),
			);
			return;
		}

		// Unknown error
		log.error('GitHub authentication error', error);
		next(
			new HttpException(
				500,
				'Authentication failed',
				'AUTH_ERROR',
				'Internal authentication error',
			),
		);
	}
}

/**
 * Optional: Middleware to authenticate with fallback to static API key
 * This allows gradual migration from API key to OIDC
 *
 * Usage:
 * router.post('/deploy/start', authenticateGitHubOrApiKey, DeployController.startDeployment);
 *
 * @unused - Available for gradual migration scenarios
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export async function authenticateGitHubOrApiKey(
	req: IRequestWithGitHub,
	res: Response,
	next: NextFunction,
): Promise<void> {
	const authHeader = req.headers.authorization;

	if (!authHeader) {
		return next(
			new HttpException(
				401,
				'Missing Authorization header',
				'AUTH_MISSING',
				'Authorization header is required',
			),
		);
	}

	// Try GitHub OIDC first
	if (authHeader.startsWith('Bearer ')) {
		const token = authHeader.substring(7).trim();

		// Check if it's a JWT (has 3 parts separated by dots)
		if (token.split('.').length === 3) {
			// Looks like a JWT - try OIDC validation
			try {
				await authenticateGitHub(req, res, next);
				return;
			} catch {
				// JWT validation failed - could be a static API key formatted as Bearer
				log.info('JWT validation failed, trying static API key fallback');
			}
		}

		// Try static API key
		const apiKey = process.env.DEPLOY_API_KEY;
		if (apiKey && token === apiKey) {
			log.info('Authenticated with static API key (fallback)');
			next();
			return;
		}
	}

	// Authentication failed
	next(
		new HttpException(
			401,
			'Invalid credentials',
			'AUTH_INVALID',
			'Authentication failed',
		),
	);
}
