name: Deploy Main Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.PROD_SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.PROD_SSH_PORT }} -H ${{ secrets.PROD_SSH_HOST }} >> /home/runner/.ssh/known_hosts

      - name: Create .env file dynamically
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
        run: |
          echo "Creating .env file dynamically..."
          echo "$ALLMYSECRETS" | jq -r '
            to_entries[]
            | select(.key | startswith("PROD_"))
            | select(.key | startswith("PROD_SSH_") | not)
            | select(.key | startswith("PROD_TEAMS_") | not)
            | select(.key | startswith("PROD_DEPLOY_BOT_") | not)
            | select(.key | ascii_downcase != "github_token")
            | "\( .key | sub("^PROD_"; "") )=\(.value)"
          ' >> .env
          echo ".env file created successfully."

      - name: Copy .env file to remote server
        env:
          SSH_PORT: ${{ secrets.PROD_SSH_PORT }}
          SSH_USER: ${{ secrets.PROD_SSH_USER }}
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
        run: |
          echo "Copying .env file to remote server using scp..."
          ssh -p $SSH_PORT -i /home/runner/.ssh/id_rsa $SSH_USER@$SSH_HOST "rm -f /home/$SSH_USER/projects/grwt-api-node-deployment-notifications-prod/.env"
          scp -P $SSH_PORT -i /home/runner/.ssh/id_rsa .env $SSH_USER@$SSH_HOST:/home/$SSH_USER/projects/grwt-api-node-deployment-notifications-prod/.env
          echo ".env file copied successfully."

      - name: Deploy Application
        run: |
          echo "Logging into the server..."
          ssh -p ${{ secrets.PROD_SSH_PORT }} -i /home/runner/.ssh/id_rsa ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} << 'EOF'
            echo "Logged into the server"
            cd /home/${{ secrets.PROD_SSH_USER }}/projects/grwt-api-node-deployment-notifications-prod/
            git checkout main
            git fetch origin
            git reset --hard origin/main
            npm i
            rm -rf lib/
            npm run build
            echo "Restarting PM2 process..."
            pm2 restart ecosystem.config.js --only grwt-api-node-deployment-notifications-prod || pm2 start ecosystem.config.js --only grwt-api-node-deployment-notifications-prod
            pm2 save
          EOF
          echo "Deployment completed successfully."
